# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tgth5HGL0B4KYb5eRnZVkORDVwPFhzxa
"""

import subprocess
import time
import cv2
import numpy as np
from flask import Flask, Response

app = Flask(__name__)

width = 640
height = 480
fps = 20
port = 9130

dict_name = "DICT_6X6_250"
draw_rejected = False

aruco_dict_map = {
    "DICT_4X4_50": cv2.aruco.DICT_4X4_50,
    "DICT_4X4_100": cv2.aruco.DICT_4X4_100,
    "DICT_4X4_250": cv2.aruco.DICT_4X4_250,
    "DICT_4X4_1000": cv2.aruco.DICT_4X4_1000,
    "DICT_5X5_50": cv2.aruco.DICT_5X5_50,
    "DICT_5X5_100": cv2.aruco.DICT_5X5_100,
    "DICT_5X5_250": cv2.aruco.DICT_5X5_250,
    "DICT_5X5_1000": cv2.aruco.DICT_5X5_1000,
    "DICT_6X6_50": cv2.aruco.DICT_6X6_50,
    "DICT_6X6_100": cv2.aruco.DICT_6X6_100,
    "DICT_6X6_250": cv2.aruco.DICT_6X6_250,
    "DICT_6X6_1000": cv2.aruco.DICT_6X6_1000,
    "DICT_7X7_50": cv2.aruco.DICT_7X7_50,
    "DICT_7X7_100": cv2.aruco.DICT_7X7_100,
    "DICT_7X7_250": cv2.aruco.DICT_7X7_250,
    "DICT_7X7_1000": cv2.aruco.DICT_7X7_1000,
    "DICT_ARUCO_ORIGINAL": cv2.aruco.DICT_ARUCO_ORIGINAL,
}

if not hasattr(cv2, "aruco"):
    raise RuntimeError("cv2.aruco not found. Install opencv-contrib-python.")

if dict_name not in aruco_dict_map:
    raise ValueError(f"unknown dict_name: {dict_name}")

aruco_dict = cv2.aruco.getPredefinedDictionary(aruco_dict_map[dict_name])
aruco_params = cv2.aruco.DetectorParameters_create()

prev_time = time.time()
fps_value = 0.0

def start_camera():
    cmd = [
        "/usr/bin/rpicam-vid",
        "-t", "0",
        "--inline",
        "--codec", "mjpeg",
        "--width", str(width),
        "--height", str(height),
        "--framerate", str(fps),
        "-o", "-"
    ]
    return subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        bufsize=0
    )

def read_jpeg_frames(process):
    buffer = b""
    while True:
        chunk = process.stdout.read(4096)
        if not chunk:
            break

        buffer += chunk

        while True:
            start = buffer.find(b"\xff\xd8")
            if start == -1:
                if len(buffer) > 2_000_000:
                    buffer = buffer[-4096:]
                break

            end = buffer.find(b"\xff\xd9", start)
            if end == -1:
                break

            jpg = buffer[start:end + 2]
            buffer = buffer[end + 2:]
            yield jpg


def detect_aruco_and_draw(frame):
    global prev_time, fps_value

    # fps calc
    now = time.time()
    dt = now - prev_time
    prev_time = now
    if dt > 0:
        fps_value = 1.0 / dt

    # detect
    (corners, ids, rejected) = cv2.aruco.detectMarkers(
        frame, aruco_dict, parameters=aruco_params
    )

    # draw detected markers
    if ids is not None and len(corners) > 0:
        ids_flat = ids.flatten()

        for (marker_corners, marker_id) in zip(corners, ids_flat):
            pts = marker_corners.reshape((4, 2))
            (top_left, top_right, bottom_right, bottom_left) = pts

            top_left = (int(top_left[0]), int(top_left[1]))
            top_right = (int(top_right[0]), int(top_right[1]))
            bottom_right = (int(bottom_right[0]), int(bottom_right[1]))
            bottom_left = (int(bottom_left[0]), int(bottom_left[1]))

            # box
            cv2.line(frame, top_left, top_right, (0, 255, 0), 2)
            cv2.line(frame, top_right, bottom_right, (0, 255, 0), 2)
            cv2.line(frame, bottom_right, bottom_left, (0, 255, 0), 2)
            cv2.line(frame, bottom_left, top_left, (0, 255, 0), 2)

            # center
            cx = int((top_left[0] + bottom_right[0]) / 2.0)
            cy = int((top_left[1] + bottom_right[1]) / 2.0)
            cv2.circle(frame, (cx, cy), 4, (0, 0, 255), -1)

            # id text
            cv2.putText(frame, str(marker_id),
                        (top_left[0], top_left[1] - 10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.7,
                        (0, 255, 0), 2)

    # show rejected candidates
    if draw_rejected and rejected is not None and len(rejected) > 0:
        cv2.aruco.drawDetectedMarkers(frame, rejected, borderColor=(0, 0, 255))

    cv2.putText(frame, f"dict: {dict_name}", (10, 25),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)
    cv2.putText(frame, f"fps: {fps_value:.1f}", (10, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)

    return frame


def generate_frames():
    process = start_camera()

    try:
        for jpg in read_jpeg_frames(process):
            # decode jpeg in bgr
            np_arr = np.frombuffer(jpg, np.uint8)
            frame = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
            if frame is None:
                continue

            frame = cv2.resize(frame, (width, height))

            # detect + draw
            frame = detect_aruco_and_draw(frame)

            # encode back to jpeg
            ok, encoded = cv2.imencode(".jpg", frame, [cv2.IMWRITE_JPEG_QUALITY, 80])
            if not ok:
                continue

            out_jpg = encoded.tobytes()

            yield (b"--frame\r\n"
                   b"Content-Type: image/jpeg\r\n\r\n" + out_jpg + b"\r\n")

    finally:
        try:
            process.terminate()
            process.kill()
        except:
            pass


@app.route("/video_feed")
def video_feed():
    return Response(generate_frames(),
                    mimetype="multipart/x-mixed-replace; boundary=frame")


@app.route("/")
def index():
    return """
    <html>
      <body style="background:#000; display:flex; flex-direction:column; align-items:center; justify-content:center; height:100vh; margin:0;">
        <div style="margin-bottom:10px; font-family:monospace; color:#ccc;">
          ArUco stream
        </div>
        <img src="/video_feed" style="max-width:100%; border:2px solid #333;">
      </body>
    </html>
    """


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=port, threaded=True)